org: abelani
app: aws-node-project
service: aws-node-project

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  handler:
    handler: handler.handler
    events:
      - http: 
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
- serverless-offline
